---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: twallet
  name: twallet
  namespace: default
  resourceVersion: '149491'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/name: twallet
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/name: twallet
    spec:
      containers:
        - image: 'registry-vpc.cn-hongkong.aliyuncs.com/omni-new/twallet:{{IMAGE_VERSION}}'
          imagePullPolicy: IfNotPresent
          name: twallet
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: ali-hk-vpc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: twallet
  name: twallet
  namespace: default
  resourceVersion: '141499'
spec:
  clusterIP: 10.43.92.29
  clusterIPs:
    - 10.43.92.29
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/name: twallet
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: twallet
  name: twallet
  namespace: default
  resourceVersion: '141535'
spec:
  ingressClassName: nginx
  rules:
    - host: twallet.omnifield.xyz
      http:
        paths:
          - backend:
              service:
                name: twallet
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - twallet.omnifield.xyz
      secretName: omnifield.xyz

